name: terraform-deployment

on: 
  workflow_dispatch:
    inputs:
      action:
        description: 'Terraform action (apply or destroy)'
        required: true
        default: 'apply'

jobs: 
  deploy: 
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    runs-on: ubuntu-latest
    
    steps: 
    - name: Code checkout
      uses: actions/checkout@v4

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with: 
        terraform_version: 1.12.2

    - name: Terraform Init and PlanN
      run: |
        terraform init

    - name: Terraform Action
      run: terraform ${{ github.event.inputs.action }} --auto-approve

